name: 'Devbox Package Updater'
description: 'Automatically check and update Devbox packages in devbox.json and devbox.lock files'
author: 'Devbox Community'

inputs:
  token:
    description: 'GitHub token for creating pull requests and accessing repository content'
    required: true
    default: ${{ github.token }}
  
  devbox-version:
    description: 'Version of Devbox to install'
    required: false
    default: 'latest'
  
  branch-prefix:
    description: 'Prefix for update branch names'
    required: false
    default: 'devbox-updates'
  
  pr-title:
    description: 'Title template for pull requests'
    required: false
    default: 'Update Devbox packages'
  
  pr-body-template:
    description: 'Template for pull request body content'
    required: false
    default: |
      ## Devbox Package Updates
      
      This PR contains automatic updates for Devbox packages.
      
      ### Updated Packages
      {updates}
      
      ### Summary
      {summary}
      
      Please review the changes and test your development environment before merging.
  
  max-retries:
    description: 'Maximum number of retries for network operations'
    required: false
    default: '3'
  
  retry-delay:
    description: 'Initial delay in seconds for retry operations'
    required: false
    default: '1'
  
  update-latest:
    description: 'Whether to refresh lock files for packages marked as "latest"'
    required: false
    default: 'false'
  
  config-path:
    description: 'Path to devbox.json configuration file'
    required: false
    default: 'devbox.json'
  
  skip-packages:
    description: 'Comma-separated list of packages to skip during updates'
    required: false
    default: ''
  
  dry-run:
    description: 'Run in dry-run mode without making actual changes'
    required: false
    default: 'false'

outputs:
  changes:
    description: 'Whether any package updates were found and applied'
  
  update-summary:
    description: 'Summary of all package updates'
  
  pr-number:
    description: 'Pull request number if created'
  
  pr-url:
    description: 'URL of the created or updated pull request'
  
  pr-updated:
    description: 'Whether an existing PR was updated'
  
  existing-pr-found:
    description: 'Whether an existing update PR was found'
  
  updated-packages:
    description: 'JSON array of updated package information'
  
  skipped-packages:
    description: 'JSON array of packages that were skipped due to errors'
  
  error-message:
    description: 'Error message if the action failed'

permissions:
  contents: write
  pull-requests: write
  metadata: read

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'blue'